@startuml
    title Two Factor Authenticate Generate QrCode
    actor "User agent" as user
    autonumber

    user -> WebService: @POST /users/google/2FAuth/qrCode (email,password)
    activate WebService

    WebService -> UseCase: generateQRCode(email,password)
    activate UseCase

    UseCase -> UseCase: validateCode(email,code)
    UseCase -->> WebService: User

    WebService -> Repository: authenticate(email,password)
    activate Repository
    Repository --> Repository: authenticate(email,password)
    Repository -->> WebService: Uni<User>
    deactivate Repository

    WebService -> WebService: secretKey = generateSecretKey()
    WebService -> WebService: user.setUsing2FA(true)
    WebService -> WebService: user.setSecret2FA(secretKey)
    WebService -> Repository: updateUser(user)
    Repository -->> WebService: Uni<User>
    deactivate UseCase

    WebService -> GoogleUtils: getGoogleAuthenticatorBarCode(secretKey,userEmail, issuer)
    activate GoogleUtils
    GoogleUtils --> GoogleUtils: getGoogleAuthenticatorBarCode(secretKey,userEmail, issuer)
    GoogleUtils -->> WebService: String barCodeData
    WebService -> GoogleUtils: createQrCode(barCodeData)
    GoogleUtils --> GoogleUtils: createQrCode(barCodeData)
    GoogleUtils -->> WebService: byte[] qrCode
    deactivate GoogleUtils

    WebService -->> user: QrCode Image (image/png)
    deactivate WebService
@enduml
