@startuml
    title Two Factor Authenticate Validate Code
    actor "User agent" as user
    autonumber
    
    user -> WebService: @POST /users/google/2FAuth/validate (email,code)
    activate WebService 

    WebService -> UseCase: validateCode(email,code)
    activate UseCase

    UseCase -> UseCase: validateCode(email,code)
    UseCase -->> WebService: User

    WebService -> Repository: findUserByEmail(email)
    activate Repository
    Repository --> Repository: findUserByEmail(email)
    Repository -->> WebService: Uni<User>
    deactivate Repository

    WebService -> WebService: Validate user.isUsing2FA()
    WebService -> WebService: secret = user.getSecret2FA()
    WebService -> GoogleUtils: getTOTPCode(secret)
    activate GoogleUtils
    GoogleUtils --> GoogleUtils: getTOTPCode(secret)
    GoogleUtils -->> WebService: String expectedCode
    deactivate GoogleUtils
    
    WebService -> WebService: Validate code.equals(expectedCode)
    WebService -> WebService: generateJWT(user)
    WebService -->> user: LoginResponseDTO (JSON with JWT token)
    deactivate WebService
@enduml
